// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NIGg1Uk_1YsDOep2uhQLQYgo805Yn8E',
    appId: '1:846508863669:web:435e74731daab6512e8efc',
    messagingSenderId: '846508863669',
    projectId: 'e-commerce-shopping-app-123',
    authDomain: 'e-commerce-shopping-app-123.firebaseapp.com',
    storageBucket: 'e-commerce-shopping-app-123.appspot.com',
    measurementId: 'G-X32SD8C4R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQshC7Lc_sQVzqvCUO9J7GNWh3NEWoZ_A',
    appId: '1:846508863669:android:75c94557240bf8282e8efc',
    messagingSenderId: '846508863669',
    projectId: 'e-commerce-shopping-app-123',
    storageBucket: 'e-commerce-shopping-app-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_sB-U11yTt7XzyyBLBAAI3it3u_VsdQU',
    appId: '1:846508863669:ios:2eca3512677ca16e2e8efc',
    messagingSenderId: '846508863669',
    projectId: 'e-commerce-shopping-app-123',
    storageBucket: 'e-commerce-shopping-app-123.appspot.com',
    androidClientId: '846508863669-lr28j6eaic2gqucfhc3k16l88lor2in2.apps.googleusercontent.com',
    iosClientId: '846508863669-qe5qt9blckdjh404kv2t7t8v8gur3ce8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NIGg1Uk_1YsDOep2uhQLQYgo805Yn8E',
    appId: '1:846508863669:web:72a2debc204b4e352e8efc',
    messagingSenderId: '846508863669',
    projectId: 'e-commerce-shopping-app-123',
    authDomain: 'e-commerce-shopping-app-123.firebaseapp.com',
    storageBucket: 'e-commerce-shopping-app-123.appspot.com',
    measurementId: 'G-EHJ0C2HZRP',
  );
}
